### PR TITLE
Timestamps

### PR DESCRIPTION
**Pull request by yofukashino**
added option to change the RPC timestamp to system uptime.
made it a drop-down menu to select either off, system, or RPC.
and btw "Experimental: RPC Event Injection" ain't working

### CODE REVIEW

**Comment by yofukashino** [comment]
yeah and added myself into authors because "pull request" you can remove it if you wanna

**Comment by Faelayis** [comment]
this branch has conflicts in the current branch, because I rely on formatter code.

**Comment by Faelayis** [comment]
u can collab with me if u want please check the notification.

**Comment by yofukashino** [comment]
okay wait

**Pull request closed without merging**
